# ETL

### Importo  Librerías

In [1]:
import pandas as pd
import numpy as np
import ast

### Cargo Dataset

In [2]:
#No se puede realizar una carga directa, entonces primero lo convierto en una lista de python por lineas.
rows = []
with open('Datasets\steam_games.json') as file:
    for line in file.readlines():
        rows.append(ast.literal_eval(line))

In [3]:
#Creo el DataFrame y reviso los registros.
df = pd.DataFrame(rows)

df

publisher                                             genres   
0             Kotoshiro      [Action, Casual, Indie, Simulation, Strategy]  \
1      Making Fun, Inc.               [Free to Play, Indie, RPG, Strategy]   
2          Poolians.com  [Casual, Free to Play, Indie, Simulation, Sports]   
3                  彼岸领域                        [Action, Adventure, Casual]   
4                   NaN                                                NaN   
...                 ...                                                ...   
32130   Ghost_RUS Games              [Casual, Indie, Simulation, Strategy]   
32131            Sacada                          [Casual, Indie, Strategy]   
32132      Laush Studio                        [Indie, Racing, Simulation]   
32133          SIXNAILS                                    [Casual, Indie]   
32134               NaN                                                NaN   

                       app_name                     title   
0           Lost Summoner Kitty       Lost Summoner Kitty  \
1                     Ironbound                 Ironbound   
2       Real Pool 3D - Poolians   Real Pool 3D - Poolians   
3                       弹炸人2222                   弹炸人2222   
4                 Log Challenge                       NaN   
...                         ...                       ...   
32130            Colony On Mars            Colony On Mars   
32131  LOGistICAL: South Africa  LOGistICAL: South Africa   
32132             Russian Roads             Russian Roads   
32133       EXIT 2 - Directions       EXIT 2 - Directions   
32134               Maze Run VR                       NaN   

                                                     url release_date   
0      http://store.steampowered.com/app/761140/Lost_...   2018-01-04  \
1      http://store.steampowered.com/app/643980/Ironb...   2018-01-04   
2      http://store.steampowered.com/app/670290/Real_...   2017-07-24   
3         http://store.steampowered.com/app/767400/2222/   2017-12-07   
4      http://store.steampowered.com/app/773570/Log_C...          NaN   
...                                                  ...          ...   
32130  http://store.steampowered.com/app/773640/Colon...   2018-01-04   
32131  http://store.steampowered.com/app/733530/LOGis...   2018-01-04   
32132  http://store.steampowered.com/app/610660/Russi...   2018-01-04   
32133  http://store.steampowered.com/app/658870/EXIT_...   2017-09-02   
32134  http://store.steampowered.com/app/681550/Maze_...          NaN   

                                                    tags  discount_price   
0          [Strategy, Action, Indie, Casual, Simulation]            4.49  \
1      [Free to Play, Strategy, Indie, RPG, Card Game...             NaN   
2      [Free to Play, Simulation, Sports, Casual, Ind...             NaN   
3                            [Action, Adventure, Casual]            0.83   
4                        [Action, Indie, Casual, Sports]            1.79   
...                                                  ...             ...   
32130              [Strategy, Indie, Casual, Simulation]            1.49   
32131                          [Strategy, Indie, Casual]            4.24   
32132                        [Indie, Simulation, Racing]            1.39   
32133  [Indie, Casual, Puzzle, Singleplayer, Atmosphe...             NaN   
32134  [Early Access, Adventure, Indie, Action, Simul...             NaN   

                                             reviews_url   
0      http://steamcommunity.com/app/761140/reviews/?...  \
1      http://steamcommunity.com/app/643980/reviews/?...   
2      http://steamcommunity.com/app/670290/reviews/?...   
3      http://steamcommunity.com/app/767400/reviews/?...   
4      http://steamcommunity.com/app/773570/reviews/?...   
...                                                  ...   
32130  http://steamcommunity.com/app/773640/reviews/?...   
32131  http://steamcommunity.com/app/733530/reviews/?...   
32132  http://

### Reviso las columnas, los tipos de datos y realizo las transformaciones.

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32135 entries, 0 to 32134
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   publisher       24083 non-null  object 
 1   genres          28852 non-null  object 
 2   app_name        32133 non-null  object 
 3   title           30085 non-null  object 
 4   url             32135 non-null  object 
 5   release_date    30068 non-null  object 
 6   tags            31972 non-null  object 
 7   discount_price  225 non-null    float64
 8   reviews_url     32133 non-null  object 
 9   specs           31465 non-null  object 
 10  price           30758 non-null  object 
 11  early_access    32135 non-null  bool   
 12  id              32133 non-null  object 
 13  developer       28836 non-null  object 
 14  sentiment       24953 non-null  object 
 15  metascore       2677 non-null   object 
dtypes: bool(1), float64(1), object(14)
memory usage: 3.7+ MB


#### "Publisher"

In [5]:
#Cantidad de valores NaN
nan_publisher = df["publisher"].isna().sum()
print(nan_publisher)      
# Reemplazo valores NaN por "Unknown"
df["publisher"].fillna("Unknown", inplace=True)
all_nan_publi = df["publisher"].isna().sum()
print(all_nan_publi)

8052
0


In [6]:
#Verificamos que todos los valores de la columan sean 'str'
print(all(isinstance(x, str) for x in df['publisher']))
print(df['publisher'].apply(type).value_counts()) 

True
publisher
<class 'str'>    32135
Name: count, dtype: int64


#### "Genres" and "Tags"

In [7]:
# Cantidad de valores nulos en la columna "genres"
cant_nan_genres = df["genres"].isna().sum()
print(cant_nan_genres)

3283


In [8]:
# Relleno los nulos en "genres" con los valores de "tags"
df['genres'].fillna(df['tags'], inplace=True)

In [9]:
# Cantidad de valores NaN en la columna "genres"
cant_nan_genres1 = df["genres"].isna().sum()
cant_nan_genres1

139

In [10]:
#Verificamos que tipos de valores hay.
print(all(isinstance(x, str) for x in df['genres']))
print(df['genres'].apply(type).value_counts())

False
genres
<class 'list'>     31996
<class 'float'>      139
Name: count, dtype: int64


In [11]:
df.drop(columns=['tags'], inplace=True) #Elimino la columna tags por ser irrelevante al tener la columna genres

#### "Title" and "App_name"

In [12]:
#Relleno los nulos en la columna "title" con los valores de "app_name".
df['title'] = df.apply(lambda row: row['app_name'] if pd.isnull(row['title']) else row['title'], axis=1)

#Elimino la columna "app_name"
df = df.drop(columns = 'app_name') 

In [13]:
# Reemplazo valores NaN por "Unknown"
df["title"].fillna("Unknown", inplace=True)

In [14]:
#Verificamos que tipos de valores hay.
print(all(isinstance(x, str) for x in df['title']))
print(df['title'].apply(type).value_counts())

True
title
<class 'str'>    32135
Name: count, dtype: int64


#### "url" and "reviews_url "

In [15]:
#Elimino las columnas porque no las considero relevantes en este caso.
df = df.drop(columns=['url', 'reviews_url'])

#### "Release_date"

In [16]:
df['release_date'] = pd.to_datetime(df['release_date'], errors='coerce')

In [17]:
df['year'] = df['release_date'].dt.strftime('%Y')

In [18]:
df.drop(columns=['release_date'], inplace=True)

In [19]:
df['year'].apply(type).value_counts()

year
<class 'str'>      29783
<class 'float'>     2352
Name: count, dtype: int64

In [20]:
df['year'].isna().sum()

2352

In [21]:
df.dropna(subset=['year'], inplace=True)  #Como todas las funciones que piden hacer está en base al año, es mejor eliminar los registros NaN, porque no van a alterar el resultado

#### "Price"

In [22]:
num_nan_precio = df["price"].isna().sum()
num_nan_precio

1001

In [23]:
unique_precios = df['price'].unique()
print(unique_precios)

[4.99 'Free To Play' 'Free to Play' 0.99 3.99 9.99 18.99 29.99 nan 10.99
 2.99 1.59 14.99 1.99 59.99 8.99 6.99 7.99 39.99 'Free' 19.99 7.49 12.99
 5.99 2.49 15.99 1.25 24.99 17.99 61.99 3.49 11.99 13.99 'Free Demo'
 'Play for Free!' 34.99 1.49 32.99 99.99 14.95 69.99 16.99 79.99 49.99 5.0
 44.99 13.98 29.96 119.99 109.99 149.99 771.71 'Install Now' 21.99 89.99
 'Play WARMACHINE: Tactics Demo' 0.98 139.92 4.29 64.99 'Free Mod' 54.99
 74.99 'Install Theme' 0.89 'Third-party' 0.5 'Play Now' 299.99 1.29 3.0
 15.0 5.49 23.99 49.0 20.99 10.93 1.39 'Free HITMAN™ Holiday Pack' 36.99
 4.49 2.0 4.0 234.99 1.95 1.5 199.0 189.0 6.66 27.99 10.49 129.99 179.0
 26.99 399.99 31.99 399.0 20.0 40.0 3.33 22.99 320.0 38.85 71.7 995.0
 27.49 3.39 6.0 19.95 499.99 199.99 16.06 4.68 131.4 44.98 202.76 1.0 2.3
 0.95 172.24 249.99 2.97 10.96 10.0 30.0 2.66 6.48 19.29 11.15
 'Play the Demo' 99.0 87.94 599.0 0.49 9.98 9.95 7.0 'Starting at $499.00'
 'Starting at $449.00' 12.89 6.49 1.87 42.99 41.99 289.99 'Free 

In [24]:
df['price'] = df['price'].replace('Starting at $499.00', 499.0)
df['price'] = df['price'].replace('Starting at $449.00', 449.0)
df['price'] = df['price'].replace('Free to Play', 0.0)
df['price'] = df['price'].replace('Free To Play', 0.0)
df['price'] = df['price'].replace('Free', 0.0)
df['price'] = df['price'].replace('Free Demo', 0.0)
df['price'] = df['price'].replace('Play for Free!', 0.0)
df['price'] = df['price'].replace('Play WARMACHINE: Tactics Demo', 0.0)
df['price'] = df['price'].replace('Free Mod', 0.0)
df['price'] = df['price'].replace('Free HITMAN™ Holiday Pack', 0.0)
df['price'] = df['price'].replace('Play the Demo', 0.0)
df['price'] = df['price'].replace('Free to Try', 0.0)
df['price'] = df['price'].replace('Free Movie', 0.0)
df['price'] = df['price'].replace('Free to Use', 0.0)

In [25]:
#Elimino los registros nulo porque son rendundantes si el objetivo es predecir el precio de un videojuego.
df = df.drop(df[df['price'].isin(['Install Now', 'Install Theme','Third-party', 'Play Now'])].index)
df = df.dropna(subset = ['price'])

In [26]:
#Verificamos que tipos de valores hay.
print(all(isinstance(x, float) for x in df['price']))
print(df['price'].apply(type).value_counts())

True
price
<class 'float'>    28776
Name: count, dtype: int64


#### "Developer"

In [27]:
#Reemplazo valores NaN por "Unknown"
df["developer"].fillna("Unknown", inplace=True)
num_nan_developer = df["developer"].isna().sum()
print(num_nan_developer)

0


In [28]:
#Verificamos que tipos de valores hay.
print(all(isinstance(x, str) for x in df['developer']))
print(df['developer'].apply(type).value_counts())

True
developer
<class 'str'>    28776
Name: count, dtype: int64


#### "Sentiment"

In [29]:
df['sentiment'].unique()

array([nan, 'Mostly Positive', 'Mixed', '1 user reviews',
       '3 user reviews', 'Very Positive', 'Overwhelmingly Positive',
       '6 user reviews', '5 user reviews', '2 user reviews', 'Positive',
       'Mostly Negative', 'Very Negative', '9 user reviews',
       '8 user reviews', 'Negative', '4 user reviews', '7 user reviews',
       'Overwhelmingly Negative'], dtype=object)

In [30]:
#Cambiar los que no tienen una clasificación a "sin clasificación"
df['sentiment'] = df['sentiment'].str.replace(r'\d+ user reviews', 'sin clasificar', regex=True)

In [31]:
df['sentiment'].unique()

array([nan, 'Mostly Positive', 'Mixed', 'sin clasificar', 'Very Positive',
       'Overwhelmingly Positive', 'Positive', 'Mostly Negative',
       'Very Negative', 'Negative', 'Overwhelmingly Negative'],
      dtype=object)

In [32]:
print(all(isinstance(x, str) for x in df['sentiment']))
print(df['sentiment'].apply(type).value_counts())

False
sentiment
<class 'str'>      22369
<class 'float'>     6407
Name: count, dtype: int64


#### "Metascore"

In [33]:
df['metascore'].unique()

array([nan, 96, 84, 80, 76, 70, 'NA', 69, 81, 75, 72, 66, 67, 77, 91, 89,
       83, 88, 65, 94, 57, 86, 87, 92, 79, 82, 58, 74, 85, 90, 68, 71, 60,
       73, 59, 64, 61, 54, 53, 78, 51, 44, 63, 38, 56, 49, 52, 62, 93, 48,
       34, 95, 43, 55, 24, 46, 41, 20, 39, 45, 35, 47, 40, 36, 50, 32, 37,
       33, 42, 29, 30], dtype=object)

In [34]:
# Reemplazar 'NA' con NaN
df['metascore'].replace('NA', np.nan, inplace=True)

In [35]:
df['metascore'].unique()

array([nan, 96., 84., 80., 76., 70., 69., 81., 75., 72., 66., 67., 77.,
       91., 89., 83., 88., 65., 94., 57., 86., 87., 92., 79., 82., 58.,
       74., 85., 90., 68., 71., 60., 73., 59., 64., 61., 54., 53., 78.,
       51., 44., 63., 38., 56., 49., 52., 62., 93., 48., 34., 95., 43.,
       55., 24., 46., 41., 20., 39., 45., 35., 47., 40., 36., 50., 32.,
       37., 33., 42., 29., 30.])

In [36]:
print(all(isinstance(x, float) for x in df['metascore']))
print(df['metascore'].apply(type).value_counts())

True
metascore
<class 'float'>    28776
Name: count, dtype: int64


In [37]:
df.shape

(28776, 12)

In [38]:
df

publisher                                             genres   
0                Kotoshiro      [Action, Casual, Indie, Simulation, Strategy]  \
1         Making Fun, Inc.               [Free to Play, Indie, RPG, Strategy]   
2             Poolians.com  [Casual, Free to Play, Indie, Simulation, Sports]   
3                     彼岸领域                        [Action, Adventure, Casual]   
5      Trickjump Games Ltd                    [Action, Adventure, Simulation]   
...                    ...                                                ...   
32129      Bidoniera Games                 [Action, Adventure, Casual, Indie]   
32130      Ghost_RUS Games              [Casual, Indie, Simulation, Strategy]   
32131               Sacada                          [Casual, Indie, Strategy]   
32132         Laush Studio                        [Indie, Racing, Simulation]   
32133             SIXNAILS                                    [Casual, Indie]   

                          title  discount_price   
0           Lost Summoner Kitty            4.49  \
1                     Ironbound             NaN   
2       Real Pool 3D - Poolians             NaN   
3                       弹炸人2222            0.83   
5         Battle Royale Trainer             NaN   
...                         ...             ...   
32129              Kebab it Up!            1.69   
32130            Colony On Mars            1.49   
32131  LOGistICAL: South Africa            4.24   
32132             Russian Roads            1.39   
32133       EXIT 2 - Directions             NaN   

                                                   specs price  early_access   
0                                        [Single-player]  4.99         False  \
1      [Single-player, Multi-player, Online Multi-Pla...   0.0         False   
2      [Single-player, Multi-player, Online Multi-Pla...   0.0         False   
3                                        [Single-player]  0.99         False   
5                    [Single-player, Steam Achievements]  3.99         False   
...                                                  ...   ...           ...   
32129   [Single-player, Steam Achievements, Steam Cloud]  1.99         False   
32130                [Single-player, Steam Achievements]  1.99         False   
32131  [Single-player, Steam Achievements, Steam Clou...  4.99         False   
32132  [Single-player, Steam Achievements, Steam Trad...  1.99         False   
32133   [Single-player, Steam Achievements, Steam Cloud]  4.99         False   

           id                 developer        sentiment  metascore  year  
0      761140                 Kotoshiro              NaN        NaN  2018  
1      643980          Secret Level SRL  Mostly Positive        NaN  2018  
2      670290              Poolians.com  Mostly Positive        NaN  2017  
3      767400                      彼岸领域              NaN        NaN  2017  
5      772540       Trickjump Games Ltd            Mixed        NaN  2018  
...       ...                       ...              ...        ...   ...  
32129  745400           Bidoniera Games   sin clasificar        NaN  2018  
32130  773640        Nikita "Ghost_RUS"              NaN        NaN  2018  
32131  733530                    Sacada              NaN        NaN  2018  
32132  610660  Laush Dmitriy Sergeevich              NaN        NaN  2018  
32133  658870             xropi,stev3ns   sin clasificar        NaN  2017  

[28776 rows x 12 columns]